name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: Jimver/cuda-toolkit@v0.2.16
        with:
          cuda: '12.5.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build
        shell: cmd
        run: nvcc -O3 -arch=sm_86 -allow-unsupported-compiler -Xcompiler "/O2 /MD" -o vanity_gpu.exe vanity.cu

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: Jimver/cuda-toolkit@v0.2.16
        with:
          cuda: '12.5.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Build
        run: nvcc -O3 -arch=sm_86 -o vanity_gpu vanity.cu
